title: Blue Line Ethics
description: Ethical Issues in Computing — CS 377, UIC

url: "https://jackbandy.com"
baseurl: "/ethical-issues-in-computing-uic"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Don't process these with Jekyll
exclude:
  - "*.csv"
  - "*.bib"
  - in-progress/
